### ISSUE TITLE
General Notes 

### ISSUE THREAD

**Issue by AmranElmasri** [GSG-G11/team-7-autocomplete-website#18]
I liked your project idea it's really great, your design is beautiful and you chose a good API for this kind of projects and you can know the site of any country after writing it. Really, it is a great work and your refactoring of your code is very nice but there is an empty file (app.js) and There is no testing .
finally, I appreciate your work and you did a great job at this project in this period of time 👏.

**Comment by AhmedQeshta** [comment]
Thank you for these notes.
